on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  TARGET: rsswall-latest-linux-amd64.tar.gz

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install golang binutils
        go build
        strip rsswall
        tar cvzf ${{env.TARGET}} rsswall feeds.example README.md


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: ${{env.TARGET}}

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: packages
            path: ${{env.TARGET}}

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: ${{env.TARGET}}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
